# Generated: Wed Apr 28 06:43:24 PDT 2021
absyn.cmi :
dumper.cmo : \
    absyn.cmi \
    dumper.cmi
dumper.cmx : \
    absyn.cmi \
    dumper.cmi
dumper.cmi : \
    absyn.cmi
dumper.cmi : \
    absyn.cmi
etc.cmo : \
    etc.cmi
etc.cmx : \
    etc.cmi
etc.cmi :
interp.cmo : \
    tables.cmi \
    etc.cmi \
    dumper.cmi \
    absyn.cmi \
    interp.cmi
interp.cmx : \
    tables.cmx \
    etc.cmx \
    dumper.cmx \
    absyn.cmi \
    interp.cmi
interp.cmi : \
    absyn.cmi
main.cmo : \
    scanner.cmo \
    parser.cmi \
    interp.cmi \
    etc.cmi
main.cmx : \
    scanner.cmx \
    parser.cmx \
    interp.cmx \
    etc.cmx
parser.cmo : \
    etc.cmi \
    absyn.cmi \
    parser.cmi
parser.cmx : \
    etc.cmx \
    absyn.cmi \
    parser.cmi
parser.cmi : \
    absyn.cmi
scanner.cmo : \
    parser.cmi \
    etc.cmi
scanner.cmx : \
    parser.cmx \
    etc.cmx
tables.cmo : \
    etc.cmi \
    absyn.cmi \
    tables.cmi
tables.cmx : \
    etc.cmx \
    absyn.cmi \
    tables.cmi
tables.cmi : \
    absyn.cmi
tables.cmi : \
    absyn.cmi
